### PR TITLE
fix brightness mapping between bco and hass

### LINKED ISSUE #9: Fix brightness mapping that causes negative brightness values in bco.
Verification failed exception is thrown in bco once the brightness of a lamp is set to 0.0 in home assistant.

### PR DESCRIPTION
**Pull request by DivineThreepwood**
### :scroll: Description

Changes proposed in this pull request:
* fix brightness mapping by mapping the range [0-255] (observed) instead of [1-265] (documented) as incoming brightness value from home assistant.
* (additional) introduce PR template

### :test_tube: Test Procedure

* Start bco
* Start hass device manager
* Change a Light to 0.0 brightness via home assistant and verify that the value is 0.0 in BCO
* Change a Light to 1.0 brightness via home assistant and verify that the value is 1.0 in BCO

### CODE REVIEW

File: src/main/kotlin/org/openbase/bco/device/hass/util/HSBColorExtensions.kt [hunk 1]
```diff
@@ -8,6 +8,6 @@ fun Double.toHassSaturation(): Double = this * 100
 
 fun Double.toBCOSaturation(): Double = this / 100
 
-fun Double.toHassBrightness(): Double = this * 255 + 1
+fun Double.toHassBrightness(): Double = this * 255
 
-fun Double.toBCOBrightness(): Double = (this - 1) / 255
\ No newline at end of file
+fun Double.toBCOBrightness(): Double = (this / 255)
```
Comment (lhuxohl) [inline src/main/kotlin/org/openbase/bco/device/hass/util/HSBColorExtensions.kt]: unnecessary braces

```suggestion
fun Double.toBCOBrightness(): Double = this / 255
```

**Review by lhuxohl — CHANGES_REQUESTED** [review]

**Review by lhuxohl — APPROVED** [review]
